name: Capitalism
version: '${project.version}'
main: creativitium.revolution.capitalism.Capitalism
api-version: 1.19
authors: [ videogamesm12 ]
description: Economy plugin for Revolution
depend:
  - Foundation
  - Vault