name: Integration
version: '${project.version}'
main: creativitium.revolution.integration.Integration
api-version: 1.19
authors: [ videogamesm12 ]
description: Plugin that adds integration optionally for other plugins
depend:
  - Foundation
softdepend:
  - Administration
  - DiscordSRV