name: Revolution
version: '${project.version}'
main: creativitium.revolution.Revolution
api-version: 1.18
authors: [ videogamesm12 ]
description: The core of Creativitium
libraries:
  - org.javassist:javassist:3.29.1-GA