name: Basics
version: '${project.version}'
main: creativitium.revolution.basics.Basics
api-version: 1.19
authors: [ videogamesm12 ]
description: Alternative to Essentials for Revolution
depend:
  - Foundation