entitywipe:
  blacklists:
    entities:
      - ITEM_FRAME
      - GLOW_ITEM_FRAME
      - PAINTING
      - ARMOR_STAND
    worlds: {}

wildcard:
  placeholder: '@p'
  blacklist:
    - multirun
    - wildcard

multirun:
  placeholder: '@n'
  limits:
    cutoff: 500
    warning: 25
  blacklist:
    - multirun
    - wildcard