name: Administration
version: '${project.version}'
main: creativitium.revolution.administration.Administration
api-version: 1.19
authors: [ videogamesm12 ]
description: Administration-related commands for Revolution
depend:
  - Foundation