# --== Moderation Configuration ==-- #
# Set any of these values to true to enable their restrictions

# Lockdown - Existing players can stay, but new players cannot join the server
lockdown: false

# Maintenance - Players without the permission node "moderation.bypass.lockdown" are kicked from the server and cannot
# rejoin until the mode is disabled
maintenance: false

# Redstone can sometimes be abused with massive complicated machines to intentionally use up server resources. Disabling
#  them can prevent such occasions, but may prevent legitimate redstone contraptions from working correctly
redstone: false

# Leaves decay after a certain period of time. Disabling this mechanic prevents them from doing that, but changes how
#   survival mode gameplay works
leaves_decay: false

# Fluids like lava and water will spread out from their original block. This is often abused to grief builds in ways
#   that are difficult to repair. Disabling it will prevent that from happening, but may prevent builds like waterfalls
#   or fountains from being built correctly
fluid_spread: false

# Fluids like lava and water may sometimes cause other auxiliary issues or be abused to grief even when fluid spreads
#   are disabled. Disabling them entirely is a heavy-handed measure, and should only be done as a last resort.
lava_placement: false
water_placement: false

# Spawn eggs are often abused by the creative item community to spawn in custom entities that lag or otherwise harm
#   servers. Disabling them is a heavy-handed measure, so a compromise that allows regular mobs to spawn but without the
#   NBT is available.
# Values:
#   - true:   Prevent all forms of spawn eggs from being used. Any attempts will be flatly rejected
#   - strip:  Allow spawn eggs to work, but strip the NBT of whatever gets spawned in as a result of them
#   - false:  Allow all spawn eggs to work, even with NBT
spawn_eggs: strip

# Explosions are very often abused to grief. If you are running a creative server, you should probably set this to true.
explosions: false
