name: Regulation
version: '${project.version}'
main: creativitium.revolution.regulation.Regulation
api-version: 1.19
authors: [ videogamesm12 ]
description: Gameplay mechanic regulator for Revolution
load: STARTUP
depend:
  - Foundation